### ISSUE TITLE
Theme in `based_vscode.mp4`?

### ISSUE THREAD

**Issue by blyxyas** [insertish/nazuna-headpats#3]
It would be cool if there was some text shwoing which theme is used in the [`based_vscode.mp4`](https://user-images.githubusercontent.com/26145882/140580690-8438b5f6-7522-429b-8b4e-49c46fa41fc0.mp4) video.

cc @sussycatgirl as I think she did the recording.

**Comment by sussycatgirl** [comment]
Yeah I recorded it, but this was a long time ago and I can't find the theme's name anymore. Sorry :/
